### ISSUE TITLE
coverage with parallel

### ISSUE THREAD

**Issue by davidcorreia** [robiningelbrecht/phpunit-coverage-tools#12]
Hello,
i have been trying to work with this package, however i get no output. i suppose its because using parallel, is this an issue?

commad: `php artisan test --parallel --processes=10 --recreate-databases --runner WrapperRunner --coverage-clover=path/to/coverage.xml --min-coverage=100`

thank you

**Comment by robiningelbrecht** [comment]
Does it output something if you don't use parallel?

**Comment by robiningelbrecht** [comment]
Just checked the paratest docs, did you try this?
<img width="907" alt="image" src="https://github.com/robiningelbrecht/phpunit-coverage-tools/assets/203894/9289b8b0-fa69-42e5-8ed8-d274aec51790">

**Comment by robiningelbrecht** [comment]
If it doesn't output anything, then there's something wrong with your configuration https://github.com/robiningelbrecht/phpunit-coverage-tools#configuration.
Is the reference to your clover file correct? Is it even generated?

**Comment by davidcorreia** [comment]
simple as this 
![image](https://github.com/robiningelbrecht/phpunit-coverage-tools/assets/16776779/0cb8dce0-e399-48ed-b233-ca3857c2f050)
and i can see the xm, it has been updated

side note (i dont know if is important) https://github.com/robiningelbrecht/phpunit-coverage-tools#usage
the `-d` is not recognised (error: The "-d" option does not exist.)

**Comment by robiningelbrecht** [comment]
`the -d is not recognised (error: The "-d" option does not exist.)`

That's the problem. This plugin expects that the -d option is there. So that means, currently it is not compatible with paratest.
I'll have to implement this :)

**Comment by davidcorreia** [comment]
ofcourse :)

**Comment by robiningelbrecht** [comment]
@davidcorreia Problem was with Artisan, filtered out `--min-coverage`. I pushed a branch https://github.com/robiningelbrecht/phpunit-coverage-tools/tree/support-artisan-paratest.

Could you test against this branch and use the argument `--phpunit-min-coverage=`?

**Comment by davidcorreia** [comment]
i believe somethings missing
` The "-d" option does not exist.`
 &
` The "--phpunit-min-coverage" option does not exist.`

**Comment by robiningelbrecht** [comment]
@davidcorreia Can you pass me the exact command you are executing pls? Thanks

**Comment by davidcorreia** [comment]
`php artisan test --parallel --processes=10 --recreate-databases --runner WrapperRunner --coverage-clover=path/to/coverage.xml --phpunit-min-coverage=100`

**Comment by davidcorreia** [comment]
to help troubleshhot, i have a flesh install repo with laravel 10 (few weeks old)
https://github.com/davidcorreia/nova-redirect-login
beside the installation steps in README, these steps are also needed

- `docker-compose exec app composer require robiningelbrecht/phpunit-coverage-tools:dev-support-artisan-paratest --dev`
- `docker-compose exec app composer require brianium/paratest --dev`
- `docker-compose exec app php artisan test --parallel --processes=10 --recreate-databases --runner WrapperRunner --coverage-clover=path/to/coverage.xml --phpunit-min-coverage=100`

**Comment by davidcorreia** [comment]
I apologize for any inconvenience, but could you provide me with some feedback?

**Comment by robiningelbrecht** [comment]
I'm very sorry @davidcorreia , but I'm currently very busy and haven't had the time to investigate this.
Might take a while to be honest. Feel free to debug this yourself and create a PR if you find the bug, I'll be happy to merge!

**Comment by davidcorreia** [comment]
i believe to found a solution, witch requires a configuration on laravel project.
however im not sure how to call 

```
        (new PhpUnitExtension())->bootstrap(
            Configuration $configuration,
            Facade $facade,
            ParameterCollection $parameters
        );
```
besides the `Symfony\Component\Console\Input\ArgvInput $input`, only have the `Illuminate\Foundation\Console\Kernel $this`.
not sure how to get those values, do you have any ideia?

**Comment by robiningelbrecht** [comment]
@davidcorreia You shouldn't call the bootstrap method manually, PHPUnit will do this for you, if you enabled the extension in your phpunit.xml file.
I started debugging this a few weeks ago, and the problem is that laraval (artisan) filters out the required `-d --min-coverage` argument which this whole plugin relies upon

**Comment by davidcorreia** [comment]
were you able to trigger the `bootstrap()` from artisan command?

**Comment by robiningelbrecht** [comment]
@davidcorreia No, I wasn't trying to either, as this happens automatically by PHPUnit

**Comment by davidcorreia** [comment]
i think artisan goes over phpunit, but we can override the `kernel->terminate()` and do what we want (for example inject the params)

**Comment by davidcorreia** [comment]
@robiningelbrecht (hardcoded values) it works by overriding the `terminate()`




    /**
     * Terminate the application.
     *
     * @param  \Symfony\Component\Console\Input\InputInterface  $input
     * @param  int  $status
     * @return void
     */
    public function terminate($input, $status) : void
    {
        $relativePathToCloverXml = 'ci/codeCoverage/codeCoverage.xml';
        $minCoverage = 100;
        $rules = \RobinIngelbrecht\PHPUnitCoverageTools\MinCoverage\MinCoverageRules::fromInt(
            minCoverage: $minCoverage,
            exitOnLowCoverage: true
        );
        $cleanUpCloverXml = false;
        (new \RobinIngelbrecht\PHPUnitCoverageTools\Subscriber\Application\ApplicationFinishedSubscriber(
            $relativePathToCloverXml,
            $rules,
            $cleanUpCloverXml,
            new \RobinIngelbrecht\PHPUnitCoverageTools\Exitter(),
            \RobinIngelbrecht\PHPUnitCoverageTools\ConsoleOutput::create(),
            \RobinIngelbrecht\PHPUnitCoverageTools\Timer\SystemTimer::create(),
        ))->notify(null);
    }



any thoughts if this could be handle it self by laravel or phpunit?

also had to change the `ApplicationFinishedSubscriber->notify()` in the argument declaration `public function notify(?Finished $event): void`

**Comment by robiningelbrecht** [comment]
@davidcorreia with the branch I created (https://github.com/robiningelbrecht/phpunit-coverage-tools/pull/13), running this command should work:

`php artisan test -d --phpunit-min-coverage -d --update-snapshots --coverage-clover=path/to/clover.xml`
